// Generated by mapf-rl-core/scripts/contracts.py. DO NOT EDIT.
pub const STATION_ACTIONS_VERSION: &str = "1.1.0";
#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum StationAction {
    Pick,
    Place,
    Charge,
}
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum StationPhase {
    #[default]
    Idle,
    Running,
    Paused,
    Completed,
    Failed,
}
pub const TELEMETRY_VERSION: &str = "1.0.0";
pub const CONTRACT_VERSION: &str = "1.0.0";
pub const CONTRACT_TREE_SHA256: &str =
    "df75495f5a4eb82583af3a5f0f5f77b303210141a4e14d0290ddc9c2aa3255fe";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WsMessageType {
    CommandAck,
    OperationsEvent,
    OrderCommand,
    ReportAck,
    RobotEventReport,
    RobotStateReport,
    StreamWelcome,
}

impl WsMessageType {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::CommandAck => "command.ack",
            Self::OperationsEvent => "operations.event",
            Self::OrderCommand => "order.command",
            Self::ReportAck => "report.ack",
            Self::RobotEventReport => "robot.event.report",
            Self::RobotStateReport => "robot.state.report",
            Self::StreamWelcome => "stream.welcome",
        }
    }
}

#[repr(u8)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ActionCandidate {
    Wait = 0,
    North = 1,
    East = 2,
    South = 3,
    West = 4,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SimulatorReportIdentity {
    pub session_epoch: u64,
    pub simulator_id: String,
    pub simulator_boot_id: String,
    pub report_sequence: u64,
    pub robot_id: String,
}
