// Generated by mapf-rl-core/scripts/contracts.py. DO NOT EDIT.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct LocalMapActivation {
    pub contract_version: String,
    pub request_id: String,
    pub map_id: String,
    pub generation: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct LocalMapOption {
    pub map_id: String,
    pub map_type: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct LocalMapRuntimeAck {
    pub contract_version: String,
    pub role: String,
    pub generation: u64,
    pub boot_id: String,
    pub state: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct LocalMapRuntimeState {
    pub contract_version: String,
    pub generation: u64,
    pub phase: String,
    pub request_id: Option<String>,
    pub active_map_id: String,
    pub target_map_id: String,
    pub error: Option<String>,
    pub maps: Vec<LocalMapOption>,
    pub boot_id: String,
    pub map_type: String,
    pub fleet_ready: bool,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct LocalMapState {
    pub contract_version: String,
    pub generation: u64,
    pub phase: String,
    pub request_id: Option<String>,
    pub active_map_id: String,
    pub target_map_id: String,
    pub error: Option<String>,
    pub maps: Vec<LocalMapOption>,
}
