// Generated by mapf-rl-core/scripts/contracts.py. DO NOT EDIT.
#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AcknowledgeMotionProfilesRequest {
    pub contract_version: String,
    pub request_id: String,
    pub boot_id: String,
    pub targets: Vec<MotionProfileTarget>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CreateRobotRequest {
    pub contract_version: String,
    pub request_id: String,
    pub map: ProvisioningMap,
    pub start: StartCell,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MotionProfile {
    pub robot_id: String,
    pub version: u64,
    pub applied_version: u64,
    pub limits: MotionProfileLimits,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MotionProfileLimits {
    pub max_linear_speed_mps: f64,
    pub max_linear_acceleration_mps2: f64,
    pub max_linear_deceleration_mps2: f64,
    pub max_linear_jerk_mps3: f64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MotionProfileTarget {
    pub robot_id: String,
    pub version: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MotionProfilesOutcome {
    pub contract_version: String,
    pub profiles: Vec<MotionProfile>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MotionRoutePlan {
    pub contract_version: String,
    pub profile_version: u64,
    pub limits: MotionProfileLimits,
    pub segments: Vec<MotionRouteSegment>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MotionRouteSegment {
    pub start_column: u64,
    pub start_row: u64,
    pub end_column: u64,
    pub end_row: u64,
    pub start_simulation_time_ms: u64,
    pub end_simulation_time_ms: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProvisioningCapabilities {
    pub contract_version: String,
    pub available: bool,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProvisioningMap {
    pub map_id: String,
    pub revision: u64,
    pub content_digest_sha256: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProvisioningOutcome {
    pub contract_version: String,
    pub robot_id: String,
    pub state: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RemoveRobotRequest {
    pub contract_version: String,
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RetryRobotRequest {
    pub contract_version: String,
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RobotRemovalOutcome {
    pub contract_version: String,
    pub robot_id: String,
    pub state: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeClaimOutcome {
    pub contract_version: String,
    pub robots: Vec<RuntimeRobotClaim>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeClaimRequest {
    pub contract_version: String,
    pub boot_id: String,
    pub running_robot_ids: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeRemovalOutcome {
    pub contract_version: String,
    pub removals: Vec<RobotRemovalOutcome>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeRemovalRequest {
    pub contract_version: String,
    pub boot_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeResultRequest {
    pub contract_version: String,
    pub boot_id: String,
    pub lease_epoch: u64,
    pub failure_code: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeRobotClaim {
    pub robot_id: String,
    pub simulator_id: String,
    pub api_key: String,
    pub lease_epoch: u64,
    pub map: ProvisioningMap,
    pub start: StartCell,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SetMotionProfilesRequest {
    pub contract_version: String,
    pub request_id: String,
    pub targets: Vec<MotionProfileTarget>,
    pub limits: MotionProfileLimits,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct StartCell {
    pub column: u64,
    pub row: u64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TrafficWait {
    pub contract_version: String,
    pub reason: String,
    pub blocking_robot_ids: Vec<String>,
}
