// Generated by mapf-rl-core/scripts/contracts.py. DO NOT EDIT.
#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CreateRobotRequest {
    pub contract_version: String,
    pub request_id: String,
    pub map: ProvisioningMap,
    pub start: StartCell,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProvisioningCapabilities {
    pub contract_version: String,
    pub available: bool,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProvisioningMap {
    pub map_id: String,
    pub revision: u64,
    pub content_digest_sha256: String,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProvisioningOutcome {
    pub contract_version: String,
    pub robot_id: String,
    pub state: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RemoveRobotRequest {
    pub contract_version: String,
    pub request_id: String,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RetryRobotRequest {
    pub contract_version: String,
    pub request_id: String,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RobotRemovalOutcome {
    pub contract_version: String,
    pub robot_id: String,
    pub state: String,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeClaimOutcome {
    pub contract_version: String,
    pub robots: Vec<RuntimeRobotClaim>,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeClaimRequest {
    pub contract_version: String,
    pub boot_id: String,
    pub running_robot_ids: Vec<String>,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeRemovalOutcome {
    pub contract_version: String,
    pub removals: Vec<RobotRemovalOutcome>,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeRemovalRequest {
    pub contract_version: String,
    pub boot_id: String,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeResultRequest {
    pub contract_version: String,
    pub boot_id: String,
    pub lease_epoch: u64,
    pub failure_code: String,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeRobotClaim {
    pub robot_id: String,
    pub simulator_id: String,
    pub api_key: String,
    pub lease_epoch: u64,
    pub map: ProvisioningMap,
    pub start: StartCell,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct StartCell {
    pub column: u64,
    pub row: u64,
}
